import type { Metadata } from 'next'
import Footer from '@/components/Footer'
import { Header } from '@/components/Header'
import { Providers } from '@/components/Providers'
import { Outfit, Ovo } from 'next/font/google'
import './globals.css'

const ovo = Ovo({
  variable: '--font-ovo',
  subsets: ['latin'],
  weight: '400',
})

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
  weight: ['400', '600'],
})

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth md:scroll-pt-20 scroll-pt-16" suppressHydrationWarning>
      <body
        className={`${ovo.variable} ${outfit.variable} antialiased`}
      >
        <Providers>
          <Header />
          <main className="md:pt-20 pt-16">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
